[tools]
java = "temurin-25.0.3+9.0.LTS"
lefthook = "2"
"npm:@fission-ai/openspec" = "1.4"

[tasks]
prepare = "lefthook install"

[tasks.client]
run = "./gradlew runClient"
run_windows = "gradlew.bat runClient"

[tasks.server]
run = "./gradlew runServer"
run_windows = "gradlew.bat runServer"

[tasks.check]
run = "./gradlew check"
run_windows = "gradlew.bat check"

[tasks.fmt]
run = "./gradlew spotlessApply"
run_windows = "gradlew.bat spotlessApply"
